### ISSUE TITLE
Tried the script on westeurope

### ISSUE THREAD

**Issue by Xoib** [devedse/DeploySonarQubeToAzureContainerInstances#1]
Hi @devedse ,

Getting the following error within the ACI instance deployed: 

```
2020.07.16 16:08:20 ERROR web[][o.s.s.a.EmbeddedTomcat] Fail to start web server
org.apache.catalina.LifecycleException: Failed to initialize connector [Connector[HTTP/1.1-80]]
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:559)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:848)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:173)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:440)
	at org.sonar.server.app.EmbeddedTomcat.start(EmbeddedTomcat.java:65)
	at org.sonar.server.app.WebServer.start(WebServer.java:52)
	at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:97)
	at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:81)
	at org.sonar.server.app.WebServer.main(WebServer.java:99)
2020.07.16 16:08:20 WARN  web[][o.s.p.ProcessEntryPoint] Fail to start web
java.lang.RuntimeException: org.apache.catalina.LifecycleException: Failed to initialize connector [Connector[HTTP/1.1-80]]
	at com.google.common.base.Throwables.propagate(Throwables.java:241)
	at org.sonar.server.app.EmbeddedTomcat.start(EmbeddedTomcat.java:69)
	at org.sonar.server.app.WebServer.start(WebServer.java:52)
	at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:97)
	at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:81)
	at org.sonar.server.app.WebServer.main(WebServer.java:99)
Caused by: org.apache.catalina.LifecycleException: Failed to initialize connector [Connector[HTTP/1.1-80]]
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:559)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:848)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:173)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:440)
	at org.sonar.server.app.EmbeddedTomcat.start(EmbeddedTomcat.java:65)
	... 4 common frames omitted
2020.07.16 16:08:20 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
2020.07.16 16:08:20 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
2020.07.16 16:08:20 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 143
2020.07.16 16:08:20 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2020.07.16 16:08:20 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

```

Any advise?

**Comment by devedse** [comment]
Hi @Xoib, at the point in time I made the post that this solution worked I thought it did. But apparently some things where still broken. Eventually I simply decided against using a container and set everything up using an app service:

https://github.com/vanderby/SonarQube-AzureAppService

Hopefully that solution is good enough for you as well.

In regards to this problem I don't really see an error message. Could you maybe try digging through some of the other logs files? I ran into some issues with the app service and used SCM to find out that there's a lot more logging files hidden in some Sonar directory somewhere. What you could do is try hosting this container on your own local docker instance and then connect to it using bash. Then you should be able to view the log files as well.
